# Generated by Django 3.2.4 on 2021-07-25 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_inventory_product_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='product_price',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
