# Generated by Django 3.2.4 on 2021-07-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210725_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_description',
            field=models.TextField(default=''),
        ),
    ]
